### ISSUE TITLE
Anvil region file support?

### ISSUE THREAD

**Issue by estella144** [iRath96/webNBT#23] opened 2022-05-07 20:01 UTC
.mca files are also written in NBT, but this NBT editor fails to open .mca files. Will there be a commit fixing this?

**Comment by iRath96** [comment] 2022-05-07 20:04
Closing as a duplicate of #4.

This repository is currently not under active development. However, pull requests for such a feature are of course always welcome.

**Closed as completed by iRath96** 2022-05-07 20:04 UTC
